Basic routing and history added
nottsjs/www.nottsjs.org pull request #13
Opened 2017-03-20 12:21 UTC by spal23

'Pages' and 'Common Components' folders set up in 'Components'.  
Routing done in index.jsx.  Some test data created in there as well.  Nothing done with it yet.
Added to the readme.md file.  Feel free to edit it out.  It just seemed the right place to leave notes for any changes, but I go with the concensus on that.

2017-03-20 14:39 UTC, nomad3k requested changes

2017-03-20 14:39 UTC, nomad3k commented on package.json
> +    "release:minor": "npm version min or && npm publish && git push --follow-tags",
Typo has broken the "minor" keyword.

2017-03-20 14:39 UTC, nomad3k commented on readme.md
> +3. Loclahost:8000 accesses /source/index.html
Typo: "loclahost"

2017-03-20 14:39 UTC, nomad3k commented on readme.md
> +I have gone with browser history for now rather than hash history if someone knows what they are doing feel free to change that about.
We need to use hashHistory, because we're running it from static files, so this isn't an option.

2017-03-20 14:39 UTC, nomad3k commented on src/components/Common/Header.jsx
> +          <input value={this.props.title} onChange={this.handleChange.bind(this)}/>
Why is there a textbox here?

2017-03-20 14:39 UTC, nomad3k commented on src/components/Pages/About.jsx
> +      };
State should be used for values that mutate.  Properties for static values.

2017-03-20 14:39 UTC, nomad3k commented on src/components/Pages/About.jsx
> +  constructor (){
Never seen a constructor without a props parameter, which is passed upward.

2017-03-20 14:39 UTC, nomad3k commented on src/index.jsx
> +import { Router, Route, browserHistory } from 'react-router';
We've got to use hashHistory.

2017-03-20 14:39 UTC, nomad3k commented on src/index.jsx
> +	}]
Hmm, linter should have thrown this out for a few reasons.  There's no trailing semi-colon and the indentation is inconsistent.  I need to check the linter settings.

2017-03-20 14:39 UTC, nomad3k commented on src/index.jsx
> +    </Router>,
This version of react-router does some interesting things with nesting routes, which is cool, but they seem to have removed that in later versions, preferring to compose the pages (as you've done) so I'll leave this be.

2017-03-20 14:39 UTC, nomad3k commented on readme.md
> +
Markdown puts these all on the same line.  Turn them into a bulleted/numbered list.

2017-03-20 14:39 UTC, nomad3k commented on src/components/Common/Footer.jsx
> +}
Hmm.. linter should have complained about missing new line at end.  Github has picked it up though.

2017-03-20 14:39 UTC, nomad3k commented on src/components/Common/Footer.jsx
> +}
Why not introduce a Template class that combines Header and Footer.

```
<Header />
{this.props.children}
<Footer />
```

Then you can consume it with code like this:
```
<Template>
    <h1>Something</h1>
    <p>Something else</p>
</Template>
```

2017-03-20 15:26 UTC, spal23 commented on src/components/Common/Header.jsx
> +          <input value={this.props.title} onChange={this.handleChange.bind(this)}/>
I was using the training page to try out a couple of things.  The text box copies back to the header text immediately.  It was to see if I could introduce an input box in the props data flow.  I will strip it out.

2017-03-21 10:22 UTC, nomad3k commented
I've fixed some bits and merged it in.

2017-03-21 10:22 UTC, closed without merging